### ISSUE TITLE
Non-critical issue regarding some console spam

### ISSUE THREAD

**Issue by thesunexpress** [hlh-restart/rtsx#21]
Hello,
I'm one of the early backers of the rtsx porting bountysource effort, and my thanks to you are vast.
Just one little thing that is more of a generally insignificant 'cosmetic' issue, is a line of innocuous noise/spam to the console.
During boot, when an SD Card is not present in the slot, we observe:
`rtsx0: pci_read_config() error - reg: 0xeeffffaa`  ---which appears to be just an announcement that there's no card present.
The device is otherwise perfectly functional & performs as intended. 
Is there any way to suppress this message to the console? 

In case it matters, this occurs on a Dell XPS 9380 running FreeBSD 13.0-RELEASE & 13-STABLE & 14-CURRENT.
`rtsx0@pci0:1:0:0:	class=0xff0000 rev=0x01 hdr=0x00 vendor=0x10ec device=0x525a subvendor=0x1028 subdevice=0x08af`
`    vendor     = 'Realtek Semiconductor Co., Ltd.' `
`    device     = 'RTS525A PCI Express Card Reader' `

**Comment by hlh-restart** [comment]
First of all thank you for your support.

I update the _master_ branch which can be used for 12.2-RELEASE and upward.
I also update the _mmc_sim_ branch which can be used for recent 13.0-STABLE and CURRENT (due to update for MMCCAM).

**Comment by hlh-restart** [comment]
The version 2.1c (master branch) committed to current.
