### ISSUE TITLE
Minor bit of spam to console

### ISSUE THREAD

**Issue by schijtreiger** [hlh-restart/rtsx#5]
EXCELLENT WORK!!!!!
I'm one of the funders at the Bounty Source post for a driver for FreeBSD. Although I ended up hardly ever using the card reader, I did consider it to be the only thing to be "amiss" with my laptop. I find myself using the card reader for all sorts of unnecessary tasks now, just because I'm happy to use it finally.

The Specs:
Dell XPS 13 - model 9360 (Dell internal ID 0T3FTF)
FreeBSD nomad 12.1-STABLE FreeBSD 12.1-STABLE r361728 corvenus  amd64 1201517

pciconf -lv:
rtsx0@pci0:59:0:0:	class=0xff0000 card=0x075b1028 chip=0x525a10ec rev=0x01 hdr=0x00
    vendor     = 'Realtek Semiconductor Co., Ltd.'
    device     = 'RTS525A PCI Express Card Reader'

I've attached some images for overview.
The only minor insignificant "nag" is some spam to the console. It does not appear to cause any functional issues, and I am not even sure why it occurs. In any case, the console spam occurs with / without a card inserted and with / without data on the card. Perhaps it is just some quirk that is unique to my brand/model hardware.
For some glossy imagery:
![Screenshot_2020-06-02_14-30-24](https://user-images.githubusercontent.com/34461649/83698227-87486e00-a5c6-11ea-8a23-c20410ac91e1.png)
![Screenshot_2020-06-02_14-32-01](https://user-images.githubusercontent.com/34461649/83698229-87e10480-a5c6-11ea-9b6e-2ad19c733300.png)
![Screenshot_2020-06-03_17-50-51](https://user-images.githubusercontent.com/34461649/83698230-88799b00-a5c6-11ea-937c-472779226ded.png)

Again, thank you very much for your efforts & this should definitely make it into the FreeBSD ecosystem soon enough!

**Comment by hlh-restart** [comment]
Thanks for your test.

The timeout and soft reset seems to indicate that a card was present when the driver was loaded but the card was not detected. But strangely the device mmcsd0 was created and operational.

Did you remove and insert the card later?

Can you test that the content of the card is correct:
```
dd if=/dev/mmcsd0 of=/tmp/card bs=4M count=252
dd if= FreeBSD-13.0-CURRENT-amd-20200528-r361567-memstick.img of=/tmp/file conv=sync
cmp /tmp/card /tmp/file
```

**Comment by schijtreiger** [comment]
The timeouts & soft resets occur if a card is inserted or not. I should also mention the exact same timeouts & soft resets occur whether I load the rtsx kernel module during boot (kld_list="rtsx" in /etc/rc.conf) or if I kldload rtsx after boot & after user login; again with or without any card present.
I will do the dd tests, and also collect console output from insert/removal of an SD card, as soon as I get on the laptop... in about an hour or so.

**Comment by hlh-restart** [comment]
For your test can you use:
```
cd /sys/dev
git clone -b tweak-RTS5229-RTS525A https://github.com/hlh-restart/rtsx.git
make
make install
```

**Comment by hlh-restart** [comment]
No news is good news. So I close this issue.
